# Generated by Django 5.2.6 on 2025-09-18 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
