# Generated by Django 5.2.6 on 2025-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
