# Generated by Django 5.2.6 on 2025-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='accountability_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_amount_split',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
